// generated by react-router-hono-server/dev
import { createHonoServer } from "react-router-hono-server/cloudflare";
import type { Env } from "hono";

declare global {
    interface CloudflareEnvironment extends Env {
      [x: string]: any;
    }
  }

declare module "react-router" {
    interface AppLoadContext {
      cloudflare: {
        env: CloudflareEnvironment;
      }
    }
  }

export default await createHonoServer({
    getLoadContext(c, { build, mode  }) {
        return {
            cloudflare: {
                env: c.env as CloudflareEnvironment,
            },
        };
    },
});