// generated by react-router-hono-server/dev
import { createHonoServer } from "react-router-hono-server/cloudflare";
import { Hono, type Env } from "hono";

type AppType = {
  Bindings: {
    VALUE_FROM_CLOUDFLARE: string;
    COOKIE_SECURE: string;
    [x: string]: any;
  };
};

declare global {
  interface CloudflareEnvironment extends Env {
    [x: string]: any;
  }
}

declare module "react-router" {
  interface AppLoadContext {
    cloudflare: {
      env: CloudflareEnvironment;
    };
  }
}

const app = new Hono<AppType>();

const honoApp = await createHonoServer({
  app,
  getLoadContext(c, { build, mode }) {
    return {
      cloudflare: {
        env: c.env as CloudflareEnvironment,
      },
    };
  },
});

export default {
  fetch: honoApp.fetch,
};
